version: '2.2'
services:
  grafana:
    image: grafana/grafana:7.0.4
    ports:
      - 3000:3000
    user: "104"    
    volumes:
      - ./grafana/database/grafana.db:/var/lib/grafana/grafana.db
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: unless-stopped
    env_file:
      - ./grafana/.env
