version: '3.9'

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:8.3.3
    networks:
      - grafana
    ports:
      - 3000:3000
    user: "104"    
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: unless-stopped
    env_file:
      - ./grafana/.env
