version: '2.2'
services:
  grafana:
    image: grafana/grafana:7.3.2
    ports:
      - 3000:3000
    user: "104"    
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: unless-stopped
    env_file:
      - ./grafana/.env
